### ISSUE TITLE
remote control?

### ISSUE THREAD

**Issue by javiersanchez66666** [LELO-Devs/F1S-SDK#10]
Hello, we are a polyamorous couple 2 boys and a girl, we are going to move to different parts of the world and we would like to know if the girl can handle two F1 lelos at the same time

**Comment by goranche** [comment]
I'm sorry to say that the code we share here on GitHub isn't meant (or suitable) for direct end-user use but is rather a means to allow third-party developers easier development of various apps utilizing our hardware.

The SDK itself doesn't support remote control out of the box, nor does the app that we ship. Your idea is, however, feasible and could be implemented with the SDK (and additional libraries and code), but it would require effort from a developer (or team of developers).

I'll present this idea to some people in the company, though, maybe the situation changes in the future, but I can't promise anything, though. 😊

I wish you all the best and as little long-distance frustration as possible 🌹👍

**Comment by fabiofenoglio** [comment]
@javiersanchez66666 I am developing a wrapper solution that enables many-to-many remote control via socket but it is based on desktop computers (not mobile). 
Write me if you could find it useful!

**Comment by atlrsa** [comment]
I would find this helpful.

**Comment by fabiofenoglio** [comment]
Please head out to https://github.com/fabiofenoglio/lelo-f1-python-sdk so you can check if that's good for you.
Please take note that while Windows and Linux are supported, support for macOS is limited to command-line only at the moment.
In case of issues or help needed with the python library, please open an issue on that repository (https://github.com/fabiofenoglio/lelo-f1-python-sdk/issues)
