### ISSUE TITLE
Availability of python library

### ISSUE THREAD

**Issue by fabiofenoglio** [LELO-Devs/F1S-SDK#11]
Hello,
I wrote a python library with samples, following your published BLE specifications.
The library is available via pip and you can find it here: https://github.com/fabiofenoglio/lelo-f1-python-sdk

Maybe you could mention it on the README of this repository in order to give more options to developers that are not targeting mobile platforms ?

Thank you!

**Comment by goranche** [comment]
Thank you very much, that's awesome 👍

A section in the README with alternative libraries does sound like a good idea. We'll have someone take a look at it, and add a section like that.

Great stuff 🏆

**Comment by goranche** [comment]
@fabiofenoglio I've just added a section to our readme, we might change the format a bit in the future, but that's it for now...

again, thanks for your input and work on this 👍
