### ISSUE TITLE
Javascript PLEASE!!!

### ISSUE THREAD

**Issue by agrublev** [LELO-Devs/F1S-SDK#12]

**Comment by fabiofenoglio** [comment]
Hi @agrublev, I'm not the developer of this repo nor associated in any way; if you are interested, I'm working on a pure vanilla JS client leveraging the Web Bluetooth API.

Repository: https://github.com/fabiofenoglio/lelo-f1-web-sdk

Working demo (please, open with latest Chrome and keep the DevTools console opened): https://fabiofenoglio.github.io/lelo-f1-web-sdk/example.html

**Comment by fabiofenoglio** [comment]
AngularJS sample is available as well: https://fabiofenoglio.github.io/lelo-f1-web-sdk/example-gui.html
