### ISSUE TITLE
F1S V2

### ISSUE THREAD

**Issue by fabiofenoglio** [LELO-Devs/F1S-SDK#22]
Hello,
where can I find the BLE specifications for the newer version (F1S V2) ?
There seems to be some differences in the registers (eg I can't see the KEY STATE at 0x0a0f) that are preventing the F1S V2 from working with open-source software modeled on the specifications currently published at https://github.com/LELO-Devs/F1S-SDK#f1s-ble-reference

thank you in advance

**Comment by MattDevUK** [comment]
Is this now resolved by update of the [F1S-V2-SPEC.md](https://github.com/LELO-Devs/F1S-SDK/blob/master/F1S-V2-SPEC.md) by @AllenYin120 @fabiofenglio ?

I'm interested in helping out but haven't developed in a while. May just have a play around with the SDKs and see what's possible.

**Comment by VincentTJones** [comment]
It won’t connect to my phone and I don’t know how to do sdks

**Comment by fabiofenoglio** [comment]
@MattDevUK yes, that's it. Thanks for the pointer.
I will start working on it soon, if you'd like to help I could probably use someone to test the SDK I will try to develop with me because I don't physically own an F1sV2

**Comment by MattDevUK** [comment]
> @MattDevUK yes, that's it. Thanks for the pointer.
> I will start working on it soon, if you'd like to help I could probably use someone to test the SDK I will try to develop with me because I don't physically own an F1sV2

Sure, no problem! I got one recently and was looking to see if it had this functionality or if I could make it when I came across yours, so would be glad to help test it out!

**Comment by fabiofenoglio** [comment]
@MattDevUK thank you, could you please mail me at development(at)fabiofenoglio.it so we can get in touch?
