### ISSUE TITLE
Interest in Desktop or WebBluetooth implementations?

### ISSUE THREAD

**Issue by qdot** [LELO-Devs/F1S-SDK#4]
Hi! First off, wanted to say, this is fantastic! Really nice documentation and it's great to see sex tech companies doing more open source work. :+1: 

I've got a partial implementation of the Lelo F1s Protocol in C# over on https://github.com/buttplugio (we'd reversed the protocol), will have it ported into Rust soon also. I'd be happy to discuss helping out if you're interested in getting either desktop or WebBluetooth implementations going around the mobile SDK. :)

**Comment by goranche** [comment]
Hey 👋 
Thanks for your kind words. We (obviously 🙈) agree, more power / control should be given to the end users. This thing has been in the works for a (too) long time, but as you might expect, in the corporate world there are many hurdles when it comes to open sourcing code, but with help from our management we ... 🤔 well, managed 😅

You reverse engineered our devices? How could you 😂 😉 
Nah, great to hear you were that interested; we hope that won't be necessary in the future, we plan on supporting the community more, maybe even with other products as well 🤐 

Regarding the desktop implementation, I believe the iOS classes dealing with bluetooth should work on macOS as well. That's something I'll make sure of in the near future.
What? What other desktops? 😆

We haven't really considered web bluetooth (yet), as it's in its early stages and (IMHO) far from being finalized, but we'll offer any help we can should you (or anyone else for that matter) want to give it a go. That goes for any other implementation as well, of course 👍
