### ISSUE TITLE
Help Please

### ISSUE THREAD

**Issue by cputzier** [LELO-Devs/F1S-SDK#5]
This is a whole new world to me.  I would like to download and try different programming for my Lelo but I know NOTHING on how to do this.  I have and android phone that I use and I have downloaded the folder of SDK for android.  From there I am clueless.  Could you please help guide me through the process.  Thanks!

Chris

**Comment by goranche** [comment]
This is meant for programmers with at least some experience. If you'd really like to learn, I'd suggest you find a course on Android development (using Android studio) and follow that. Things should become clear after that. 👍 

Of course, we'll gladly help with questions specific to the SDK itself.

**Comment by goranche** [comment]
@cputzier thank you for your question, of course... 🙈 
we might create something for users with (none to) less developer experience in the future.

will keep you updated if we do start something 👍
