### ISSUE TITLE
Device stuck

### ISSUE THREAD

**Issue by Icydeadpeople225** [LELO-Devs/F1S-SDK#6]
I have ownd an F1s-Developer Red since December and it has never worked.  Pressing the power button either to confirm sync with the app or to enter "cruise control" mode does nothing.  I tried to figure out how to recompile the app and remove that check but after reading the BLE guide and using a 3rd party app to communicate with the F1s it seems the KeyState security feature is to blame.  

I am running SoftwareRevisionString F1s Rev. A and firmware F1s PRE SVN_2359.  No amount of pressing makes the KeyState flip from 0 to 1. I've seen several people complain in reviews of the same issue.  Who is working on this because customer support just tells me to wait...

**Comment by goranche** [comment]
@Icydeadpeople225 
We can't really help you with that, our customer care might be the right place to turn to.
We only support the SDK aspect here and don't have access to other aspects of the support chain.

That said, I'll try to check if there is anything with that particular version of the firmware, and will reopen this issue if I find anything.

In the mean time, have you seen this [blog post and video](https://www.lelo.com/blog/f1s-connectivity/)?
We've recorded it because the instructions were somewhat unclear 🙈

**Comment by goranche** [comment]
@Icydeadpeople225 hm... you shouldn't have the A revision of the firmware, which is kind of weird, but still shouldn't cause this many issues.
of course, having "played" the game of development for quite a while, I'm well aware that "should not cause" doesn't hold much value 🙄 

We're working on an update function that could be used by end users (like yourself), but aren't ready with it yet (I won't bore you with the usual story: limited resources and priorities 🙈 )
I'll try to see if it's something we'll be able to move along faster, and let you know when I have more info.

In the mean time, I'm reopening this issue (so it doesn't get lost) and assigning myself.
(I'm not putting the bug label on this issue as it's not really an issue with the SDK itself)

**Comment by Icydeadpeople225** [comment]
Don't know if this is related but I've got customer support working on the
issue too. (946820) I do tech support so I understand the difficulty. I've
heard a few others online complain about the same symptoms so there might
be other devices like mine.

Let me know if you need something from me.

**Comment by goranche** [comment]
well... this will have to be solved by an update function in either the SDK, or (more likely) the official app. We're working on that :+1:
I'm closing this till then, though.
