### ISSUE TITLE
Not sure specs are right

### ISSUE THREAD

**Issue by gregersn** [LELO-Devs/F1S-SDK#8]
When I test with the demo app, everything seems to work correctly. 
However, when I use the BLE-specs, or the example app (Android), there seems to be some issues. 

Both in the demo-app, and when I try to follow the specs, I am not able to stop the motors.
And when I read from the motor control, I get a value of `0x000000` back, but the spec says that the value should be `0x01yyzz`. I get `0x000000` as the motors are running. Both in my own code, and in the example android app.

**Comment by goranche** [comment]
That shouldn't be the case, of course 🤔 
I'll see if we can look into this. It's a bit tricky at the moment, with the going ons and all 🙈 

Will get back to you as soon as I find something out 😉

**Comment by gregersn** [comment]
Update: Tested more of the functions in the Android app that is available in this repo, and a lot of it  does not get information back from the device, and also, does not affect the motors in any way

Reading state of cruise control, and other functions only returns zeros in the test-app I compiled, and has no effect on the device when tried to write to it.

**Comment by goranche** [comment]
hm, that's weird, to say the least...
I don't have a device at my location at the moment, waiting for one to be delivered from our warehouse (working from home and all that, in a different country) to be able to test things... (I'm an iOS person myself, and haven't done much work with the Android code, but will when I get the hardware)

I'll get back to you when I have the hardware and see what's happening. Is your test code maybe accessible on github?
also, what hardware are you using? (The android side, I mean)

**Comment by gregersn** [comment]
No code on Github (yet), but since the example application in this repo does not even work, I guess that is a place to start, to verify on your side. 
The Android device I am using is a Xiaomi A1

**Comment by goranche** [comment]
cool, thanks... as stated, I'll get back to this thread when I get the hardware, I'm hoping that'll be this week still 😕

**Comment by fabiofenoglio** [comment]
I'm experiencing the same problem.
Motor control reads 0x000000 with the motors running after connection;
If I manually use the "+" and "-" buttons it reads 0x010104 at min speed and 0x010115 at max speed.

Any news on this?

**Comment by gregersn** [comment]
@fabiofenoglio I found that if I instead of sending the documented stop command, send 0x01, 0x00, 0x00, the motors stop. After that, if I send new speed commands, reading out the speed seems to be correct.

**Comment by fabiofenoglio** [comment]
@gregersn it works. Thank you very much!

**Comment by goranche** [comment]
@fabiofenoglio I'm guessing you're ok now?
I haven't been able to try this yet, busy with other stuff, but will get to it and update the SDK appropriately, but I'll close this issue for the time being...

If you think it's still needed, please feel free to reopen it 👍
