### ISSUE TITLE
key state failure still not solved

### ISSUE THREAD

**Issue by srquartz** [LELO-Devs/F1S-SDK#9]
Just received a device (prototype) and it's a brick. The same - now closed - issue, namely the confirmation button press does nothing and it will not get past that screen. Looked to see if there's some workaround in the SDK but doesn't see possible. This is really beyond any reasonable expectation that devices with this issue are still shipping. Is there really no tech support yet for this issue??

**Comment by goranche** [comment]
Please contact our customer care for these issues, we're here just for the SDK...
